# Generated by Django 4.0.4 on 2022-05-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('smarks', models.FloatField()),
                ('sadd', models.CharField(max_length=150)),
            ],
        ),
    ]
